### ISSUE TITLE
怎么用？

### ISSUE THREAD

**Issue by ScienceZone** [3plus10i/IDM-Batch-Download-Helper#1]
请问怎么用能说的再明白一点吗？我指的是命令提示符怎么输入？谢谢！

**Comment by 3plus10i** [comment]
启动后显示命令行窗口，程序自动检查idm的安装路径，如果找不到会提示要求输入路径。

正常情况下需要输入两个参数。第一个是存有下载链接的.csv文件的路径，第二个要保存到本地的哪个文件夹。

仓库提供了test.csv作为范例。

**Comment by ScienceZone** [comment]
有点曲折，没成功，安装了pandas后还是不行，难道是我的IDM是便携版的缘故？可是这个版本有“绿化”，应该添加到注册表中了，不知为何不成功！

E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master>python helper.py ‪E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master\test.csv
Traceback (most recent call last):
  File "helper.py", line 5, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master>python helper.py ‪E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master\test.csv
----Batch Download Files using IDM----
Columns: url  subfolder  filename
Name of CSV file in current folder or absolute path:
current folder
Wrong path!
Name of CSV file in current folder or absolute path:
E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master
Wrong path!
Name of CSV file in current folder or absolute path:
absolute path
Wrong path!
Name of CSV file in current folder or absolute path:
E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master\test.csv
>>Selected data source: E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master\test.csv
Absolute save path:
E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master
>>Selected save directory: E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master
Loading...
>>Loaded E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master\test.csv
>>Total files amount: 4
>>Transfering to IDM...
>>Estimated waiting time: 2 s.
Path of IDMan.exe:
‪E:\Toolbox\应用\下载工具\IDM\Internet Download Manager\Bin\IDMan.exe
Path of IDMan.exe:
E:\Toolbox\应用\下载工具\IDM\Internet Download Manager\Bin
……
啊哈！
居然是我“绿化”后忘记将IDM激活了！但是还有个问题，下载的文件居然没有扩展名，怎么搞的？我用这个工具下载了一下出版社分享的教材

**Comment by ScienceZone** [comment]
E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master>python helper.py
----Batch Download Files using IDM----
Columns: url  subfolder  filename
Name of CSV file in current folder or absolute path:
E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master\test.csv
>>Selected data source: E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master\test.csv
Absolute save path:
E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master
>>Selected save directory: E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master
Loading...
>>Loaded E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master\test.csv
>>Total files amount: 4
>>Transfering to IDM...
>>Estimated waiting time: 2 s.
Path of IDMan.exe:
E:\Toolbox\应用\下载工具\IDM\Internet Download Manager\Bin
>> Transfering... 100.0%

Download started!
>>Import success, plz quit and wait IDM.
请按任意键继续. . .
下载的文件没有扩展名！

**Comment by 3plus10i** [comment]
谢谢你的体验！

针对下载的文件没有拓展名的问题，一般来说，url的最后一段是服务器上的文件名，idm会从这文件名中自动解析并添加到下载的文件上。如果方便的话，请把你的资源链接csv文件发给我，我将做针对性的检查和改进。
