### ISSUE TITLE
下载文件无扩展名的问题

### ISSUE THREAD

**Issue by ScienceZone** [3plus10i/IDM-Batch-Download-Helper#2]
您好，我用它测试下载了3个文件，内容如下：

url | subfolder | filename |   |   |  
-- | -- | -- | -- | -- | --
https://oem-shanxi.oss-cn-shenzhen.aliyuncs.com/cms/news/2020-02-12/-iQKsNC6SPSXU5DG-bhkbg.pdf | book | 语文.新课标两导两练高效学案（统编版）1 |   |   |  
https://oem-shanxi.oss-cn-shenzhen.aliyuncs.com/cms/news/2020-02-12/3aJ6MlDZTq-YKoC2iUjyVQ.pdf | book | 数学.新课标两导两练高效学案（苏教版）1 |   |   |  
https://oem-shanxi.oss-cn-shenzhen.aliyuncs.com/cms/news/2020-02-12/F7gQ31ZoT4OWANHZUshtaA.pdf | book | 道德与法治.新课标两导两练高效学案（统编版）1 |   |   |  
https://oem-shanxi.oss-cn-shenzhen.aliyuncs.com/cms/news/2020-02-12/EHkZcL9qTiaAECkL_Vyo3w.pdf | book | 科学.新课标两导两练高效学案（苏教版）1 |   |   |  

竖线应该是直接粘贴的缘故。
您这个工具对付需要重命名下载的文件简直是神器，网上我知的IDM批量导入助手另外两个是ilv和韦贝贝的版本，ilv的版本编辑下载信息有些费劲，韦贝贝的版本刚开始用时差点成功，后来不知为何一点不管用了，IDM直接没反应。您的这个小家伙如果拓展名能自动加上，一条指令能将csv文件和IDM路径都告诉程序，那就完美了！总之，谢谢！

**Comment by ScienceZone** [comment]
居然能复制表格，没竖线！

**Comment by ScienceZone** [comment]
操作略微复杂，总共需要输入4条指令:
E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master>python helper.py
----Batch Download Files using IDM----
Columns: url  subfolder  filename
Name of CSV file in current folder or absolute path:
E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master\test.csv
>>Selected data source: E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master\test.csv
Absolute save path:
E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master
>>Selected save directory: E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master
Loading...
>>Loaded E:\Toolbox\应用\下载工具\IDM-Batch-Download-Helper-master\test.csv
>>Total files amount: 4
>>Transfering to IDM...
>>Estimated waiting time: 2 s.
Path of IDMan.exe:
E:\Toolbox\应用\下载工具\IDM\Internet Download Manager\Bin
>> Transfering... 100.0%

Download started!
>>Import success, plz quit and wait IDM.
请按任意键继续. . .

**Comment by 3plus10i** [comment]
感谢你的关注！

bug复现未成功。IDM在建立下载列表时会自动将url最后的拓展名增加（或替换）到自定义文件名后，建议检查IDM版本。本仓库介绍页底部提供了IDM下载资源。
尽管未能复现，但这确实是潜在的问题。未来几个版本中将手动修复此问题，敬请持续关注本项目。
